[package]
name = "bevy-game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.9.1"

# debug mode optimization
[profile.dev]
opt-level = 1

# dep optimization
[profile.dev.package."*"]
opt-level = 3
